In [43]:
import numpy as np
import pandas as pd
import seaborn as snr

In [44]:
data=pd.read_csv("/content/sample_data/Housing (1).csv")

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [46]:
data.isnull()

price   area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    False  False     False      False    False     False      False   
1    False  False     False      False    False     False      False   
2    False  False     False      False    False     False      False   
3    False  False     False      False    False     False      False   
4    False  False     False      False    False     False      False   
..     ...    ...       ...        ...      ...       ...        ...   
540  False  False     False      False    False     False      False   
541  False  False     False      False    False     False      False   
542  False  False     False      False    False     False      False   
543  False  False     False      False    False     False      False   
544  False  False     False      False    False     False      False   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0       False            False            False    False     False   
1       False            False            False    False     False   
2       False            False            False    False     False   
3       False            False            False    False     False   
4       False            False            False    False     False   
..        ...              ...              ...      ...       ...   
540     False            False            False    False     False   
541     False            False            False    False     False   
542     False            False            False    False     False   
543     False            False            False    False     False   
544     False            False            False    False     False   

     furnishingstatus  
0               False  
1               False  
2               False  
3               False  
4               False  
..                ...  
540             False  
541             False  
542             False  
543             False  
544             False  

[545 rows x 13 columns]

In [47]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [48]:
data.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [49]:
data.fillna(data.median())

<ipython-input-49-dd263c1bfef6>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.fillna(data.median())


price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [50]:
data['mainroad']=data['mainroad'].apply({'yes':1,'no':0}.get)
data['basement']=data['basement'].apply({'yes':1,'no':0}.get)
data['guestroom']=data['guestroom'].apply({'yes':1,'no':0}.get)
data['hotwaterheating']=data['hotwaterheating'].apply({'yes':1,'no':0}.get)
data['airconditioning']=data['airconditioning'].apply({'yes':1,'no':0}.get)
data['prefarea']=data['prefarea'].apply({'yes':1,'no':0}.get)
data['furnishingstatus']=data['furnishingstatus'].apply({'furnished':1,'semi-furnished':2,'unfurnished':3}.get)

In [51]:
data.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

   furnishingstatus  
0                 1  
1                 1  
2                 2  
3                 1  
4                 1

In [52]:
x=data[['area','bedrooms','bathrooms','stories','mainroad','guestroom','basement','hotwaterheating','airconditioning','parking','prefarea','furnishingstatus']]
y=data[['price']]

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [55]:
x_train.shape

(436, 12)

In [56]:
y_train.shape

(436, 1)

In [57]:
x_test.shape

(109, 12)

In [58]:
y_test.shape

(109, 1)

In [64]:
from sklearn.linear_model import LinearRegression
lregression=LinearRegression()

In [71]:
from sklearn.ensemble import RandomForestRegressor
rfregression=RandomForestRegressor(n_estimators=50,random_state=0)

In [72]:
lregression.fit(x_train,y_train)

LinearRegression()

In [73]:
rfregression.fit(x_train,y_train)

<ipython-input-73-954c12fcb989>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfregression.fit(x_train,y_train)


RandomForestRegressor(n_estimators=50, random_state=0)

In [74]:
lregression.predict(x_test)

array([[3575156.30411725],
       [2820318.77018618],
       [1988066.26296667],
       [6086819.34174595],
       [3717180.32595711],
       [6599186.51791838],
       [5161222.15334596],
       [4856002.08900617],
       [5416596.37419019],
       [7243853.15050467],
       [4030182.99448786],
       [4266243.97196279],
       [4987911.0473815 ],
       [6918510.40384344],
       [4983020.87867994],
       [2936798.40662453],
       [6459054.38278125],
       [3999816.85998079],
       [5033825.07772985],
       [2810419.87689416],
       [4231527.72772447],
       [2623671.7315577 ],
       [2221968.11663104],
       [4397233.57477157],
       [4543376.48111094],
       [7424362.95253527],
       [3336089.52085448],
       [3976302.99045981],
       [5219982.09154395],
       [3663701.93463107],
       [3105343.38115328],
       [3006280.12274224],
       [2886212.87653418],
       [6350731.98416828],
       [3042431.50182779],
       [3987035.75484014],
       [2719794.56228571],
 

In [76]:
rfregression.predict(x_test)

array([ 3615640.        ,  3082940.        ,  2424100.        ,
        5364800.        ,  4416860.        ,  6811700.        ,
        5569550.        ,  4818660.        ,  5985420.        ,
        7764400.        ,  4157720.        ,  4526200.        ,
        4252150.        ,  7086100.        ,  4378640.        ,
        3547040.        ,  7404460.        ,  3855040.        ,
        5414500.        ,  3275766.66666667,  3441491.66666667,
        3372320.        ,  3049643.33333333,  5175520.        ,
        3563420.        ,  8284875.2       ,  3214869.        ,
        4366110.        ,  4410980.        ,  3620400.        ,
        4016950.        ,  2905490.        ,  3593520.        ,
        5868100.        ,  3532760.        ,  4352600.        ,
        3266083.33333333,  5533080.        ,  6542620.        ,
        6259470.        ,  3940813.33333333,  3953670.        ,
        2925146.        ,  5057640.        ,  5869640.        ,
        2285150.        ,  3940160.     

In [77]:
lregression.score(x,y)

0.6768445885702572

In [78]:
rfregression.score(x,y)

0.8947347620210201

In [79]:
new_data={'area':7420,'bedrooms':4,'bathrooms':2,'stories':3,'mainroad':1,'guestroom':0,	'basement':0,	'hotwaterheating':0,	'airconditioning':1,	'parking':2	,'prefarea':1,'furnishingstatus':1}

In [80]:
new=pd.DataFrame(new_data,index=[1])

In [81]:
lregression.predict(new)

array([[8340373.60125163]])

In [82]:
rfregression.predict(new)

array([11375000.])